public class Board {
    private String[][] Board= new String[10][19];
    private String raw =
            "CDDDDDDDDD|CCCDDDDDCC|MMMDMMGDDC|CMMMMMFFCC|CCCMMWFFFC|PCCCMFFWTC|PPGTFFWFFT|PPTTFFPSTT|PPPTTWPPTT|PPPTWPPTTT" +
            "DDCWWTTTPP|DSCWTTTGPP|CCCFFFTCFF|CCFFWDDCCF|CPPWFFDDCC|PPGFWFWDDC|PPPTFFWWDD|PPTTMWWWDW|PMTTWWWWWW|TTTWWWWWWW" +
            "PPPTTWPTTT|PPPSTWPTTT|PFFPTTWPPT|FFCPTWFGTT|FFFCCWFFWW|MMCPPWWWDD|CCCMPFFFDD|CCSDMDFFCC|WWWDDDDMCC|WWWWDDDDDC" +
            "PPTTTWPTTF|PFTTWPTTFF|PFFTWPPFFF|FFTTWPMFDD|CFSTWPDDDD|CCTWPPMMDD|CCWWWPDDDC|WWPPWWGCMC|WDSPWMWCCC|WDDWWWWCCC" +
            "TTTTMMPMCC|TMTTFPMMMC|FFTFFFPPWM|DFFFWGPWMM|DDDDFWPWCC|DCDDDWWCPC|DDCDDWFSPC|CCGDWFFFPP|DCWWWTTFPP|DCCWTTTPPP" +
            "DDCWWTTPPP|DCWFFTTTPP|DDWFFTTGFP|WWWFPTFFFF|WWWWPPPPFF|WTTWPPCCDC|WTCTWPCCDC|WSCFWGDDCW|WWCFWWWDDW|WWWWWWWWWW" +
            "CCCDDWDDDD|MMCDDWDDDD|MMCMMWDDGF|MCMMWMDFFF|CCTTWMMCFFCTTWCCCMFF|CGTTWFFFFF|PPTWPSPFPT|PPTTWPPPPT|PPTTWPPPTT" +
            "FDDMMDDCCC|FFDDDMMCCC|FFFFFFFMMM|WWFSPPTTMM|FFWWPPPTTC|FCCWPTTCCC|DFGCWTTGCP|DDCWTTPPPP|DDDWTTTPPP|DDWWTTTPPP";
    public Board(){

    }




}
